/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-10-24 10:47:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class admin_005fproduct_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/admin/./product_write.jsp", Long.valueOf(1698144430735L));
    _jspx_dependants.put("/admin/./menu.jsp", Long.valueOf(1698137132989L));
    _jspx_dependants.put("/admin/./footer.jsp", Long.valueOf(1696323832366L));
    _jspx_dependants.put("/admin/./top.jsp", Long.valueOf(1696324062141L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

 Date apwday = new Date();
 SimpleDateFormat apwsf = new SimpleDateFormat("yyyyMMddHHmmss");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>관리자 등록 페이지</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/basic.css?v=");
      out.print(apwsf.format(apwday));
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/login.css?v=");
      out.print(apwsf.format(apwday));
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/main.css?v=");
      out.print(apwsf.format(apwday));
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/subpage.css?v=");
      out.print(apwsf.format(apwday));
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/product.css?v=");
      out.print(apwsf.format(apwday));
      out.write("\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./img/logo.png\" sizes=\"128x128\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./img/logo.png\" sizes=\"64x64\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./img/logo.png\" sizes=\"32x32\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./img/logo.png\" sizes=\"16x16\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"headercss\">\r\n");
      out.write("   ");
      out.write('\r');
      out.write('\n');

String name =(String) session.getAttribute("name");

      out.write("    \r\n");
      out.write("\r\n");
      out.write(" <div class=\"header_div\">\r\n");
      out.write("        <p><img src=\"./img/logo.png\" class=\"logo_sm\"> ADMINISTRATOR</p>\r\n");
      out.write("        <p>");
      out.print(name );
      out.write(" <a href=\"#\">[개인정보 수정]</a> <a onclick=\"logout();\" href=\"./admin_logout.do\">[로그아웃]</a></p>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("	window.onload = function(){\r\n");
      out.write("		var admin = \"");
      out.print(name);
      out.write("\";\r\n");
      out.write("		\r\n");
      out.write("		console.log(admin);\r\n");
      out.write("		if(admin == \"\" || admin==\"null\"){\r\n");
      out.write("			alert(\"정상적인 접근이아닙니다.\");\r\n");
      out.write("			location.href=\"./index.jsp\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<nav class=\"navcss\">\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("   <div class=\"nav_div\">\r\n");
      out.write("        <ol>\r\n");
      out.write("            <li title=\"쇼핑몰 회원관리\"><a href=\"./admin_mainok.do\">쇼핑몰 회원관리</a></li>\r\n");
      out.write("            <li title=\"쇼핑몰 상품관리\"><a href=\"./plists.do\">쇼핑몰 상품관리</a></li>\r\n");
      out.write("            <li title=\"쇼핑몰 기본설정\"><a href=\"./admin_config.do\">쇼핑몰 기본설정</a></li>\r\n");
      out.write("        </ol>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<main class=\"maincss\">\r\n");
      out.write("<section>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

 Date pwday = new Date();
 SimpleDateFormat pwsf = new SimpleDateFormat("yyyyMMddHHmmss");

      out.write("\r\n");
      out.write(" <p>상품 등록 페이지</p>\r\n");
      out.write(" <form id=\"ff\" method=\"post\" action=\"./product_register.do\" enctype=\"multipart/form-data\">\r\n");
      out.write("	<div class=\"product_insert\">\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>대메뉴 카테고리</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <input type=\"text\" name=\"pB_cate\" class=\"product_input1\"> \r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>소메뉴 카테고리</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <input type=\"text\" name=\"pS_cate\" class=\"product_input1\"> \r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>상품코드</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <input type=\"text\" name=\"pcode\" id=\"pcode\" class=\"product_input1\"> \r\n");
      out.write("	            <input type=\"button\" value=\"중복확인\" onclick=\"pcode_check();\" title=\"중복확인\" class=\"product_btn\"> <span class=\"help_text\">※ 상품코드는 절대 중복되지 않도록 합니다.</span>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>상품명</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <input type=\"text\" name=\"pname\" class=\"product_input2\" maxlength=\"100\"> <span class=\"help_text\">※ 상품명은 최대 100자까지만 적용할 수 있습니다.</span>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>상품 부가설명</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <input type=\"text\" name=\"pdescription\" class=\"product_input4\" maxlength=\"200\"> <span class=\"help_text\">※ 상품명은 최대 200자까지만 적용할 수 있습니다.</span>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>판매가격</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <input type=\"text\" name=\"pprice\" class=\"product_input3\" maxlength=\"7\"> <span class=\"help_text\">※ , 없이 숫자만 입력하세요 최대 7자리</span>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>할인율</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <input type=\"text\" name=\"psale\" onkeyup=\"cal(event);\" class=\"product_input3\" maxlength=\"2\" value=\"0\">% <span class=\"help_text\">※ 숫자만 입력하세요</span>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>할인가격</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <input type=\"text\" name=\"psaleprice\" class=\"product_input3\" maxlength=\"7\" value=\"0\" readonly> <span class=\"help_text\">※ 할인율이 0%일 경우 할인가격은 0으로 처리 합니다.</span>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>상품재고</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <input type=\"text\" name=\"pstock\" class=\"product_input3\" maxlength=\"4\" value=\"0\">EA <span class=\"help_text\">※ 숫자만 입력하세요. 재고가 0일 경우 soldout이 됩니다.</span>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>판매 유/무</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <label class=\"product_label\">\r\n");
      out.write("	            <input type=\"radio\" name=\"pdone\" value=\"Y\" name=\"a\" style=\"vertical-align:-1px;\" checked> 판매시작\r\n");
      out.write("	            </label>\r\n");
      out.write("	            <label class=\"product_label\">\r\n");
      out.write("	            <input type=\"radio\" name=\"pdone\" value=\"N\" style=\"vertical-align:-1px;\"> 판매종료\r\n");
      out.write("	            </label> <span class=\"help_text\">※ 숫자만 입력하세요. 재고가 0일 경우 soldout이 됩니다.</span>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul>\r\n");
      out.write("	        <li>조기품절</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <label class=\"product_label\">\r\n");
      out.write("	                <input type=\"radio\" name=\"psold\" value=\"Y\" style=\"vertical-align:-1px;\"> 사용\r\n");
      out.write("	            </label>\r\n");
      out.write("	            <label class=\"product_label\">\r\n");
      out.write("	                <input type=\"radio\" name=\"psold\" value=\"N\" style=\"vertical-align:-1px;\" checked> 미사용\r\n");
      out.write("	            </label>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul style=\"height: 160px;\">\r\n");
      out.write("	        <li>상품 대표이미지</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <ol style=\"width:100%; height: auto;\">\r\n");
      out.write("	            <li style=\"width:100%; height:45px;\">\r\n");
      out.write("	            <input type=\"file\" name=\"mfile\" value=\"\" multiple=\"multiple\">\r\n");
      out.write("	            <span class=\"help_text\">※ 상품 대표이미지 이며, 이미지 용량은 2MB 까지 입니다.</span>\r\n");
      out.write("	            </li>\r\n");
      out.write("	            </ol>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul style=\"height: 400px;\">\r\n");
      out.write("	        <li>상품 상세설명</li>\r\n");
      out.write("	        <li>\r\n");
      out.write("	            <textarea class=\"product_text1\" name=\"pdetail\"></textarea>\r\n");
      out.write("	        </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"subpage_view4\" style=\"text-align:center;\">\r\n");
      out.write("	    <input type=\"button\" value=\"상품 리스트\" title=\"상품 리스트\" onclick=\"p_list()\" class=\"p_button p_button_color1\" style=\"margin-right: 5px;\">\r\n");
      out.write("	    <input type=\"button\" value=\"상품 등록\" title=\"상품 등록\" onclick=\"p_regit()\" class=\"p_button p_button_color2\">\r\n");
      out.write("	    </span>\r\n");
      out.write("	</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/product_write.js?v=");
      out.print(pwsf.format(pwday));
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("</main>\r\n");
      out.write("<footer class=\"main_copyright\">\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write(" <div>\r\n");
      out.write("        Copyright ⓒ 2023 shopbag All rights reserved.\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
