/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-10-24 08:45:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import team2.memberDto;
import java.util.*;

public final class admin_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/admin/./menu.jsp", Long.valueOf(1698137132989L));
    _jspx_dependants.put("/admin/./footer.jsp", Long.valueOf(1696323832366L));
    _jspx_dependants.put("/admin/./top.jsp", Long.valueOf(1696324062141L));
    _jspx_dependants.put("/admin/./main.jsp", Long.valueOf(1698133181725L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("team2.memberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

 Date amday = new Date();
 SimpleDateFormat amsf = new SimpleDateFormat("yyyyMMddHHmmss");

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>관리자 등록 페이지</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/basic.css?v=");
      out.print(amsf.format(amday));
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/login.css?v=");
      out.print(amsf.format(amday));
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/main.css?v=");
      out.print(amsf.format(amday));
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/subpage.css?v=");
      out.print(amsf.format(amday));
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/product.css?v=");
      out.print(amsf.format(amday));
      out.write("\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./img/logo.png\" sizes=\"128x128\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./img/logo.png\" sizes=\"64x64\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./img/logo.png\" sizes=\"32x32\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./img/logo.png\" sizes=\"16x16\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 최상단 -->\r\n");
      out.write("<header class=\"headercss\">\r\n");
      out.write("   ");
      out.write('\r');
      out.write('\n');

String name =(String) session.getAttribute("name");

      out.write("    \r\n");
      out.write("\r\n");
      out.write(" <div class=\"header_div\">\r\n");
      out.write("        <p><img src=\"./img/logo.png\" class=\"logo_sm\"> ADMINISTRATOR</p>\r\n");
      out.write("        <p>");
      out.print(name );
      out.write(" <a href=\"#\">[개인정보 수정]</a> <a onclick=\"logout();\" href=\"./admin_logout.do\">[로그아웃]</a></p>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("	window.onload = function(){\r\n");
      out.write("		var admin = \"");
      out.print(name);
      out.write("\";\r\n");
      out.write("		\r\n");
      out.write("		console.log(admin);\r\n");
      out.write("		if(admin == \"\" || admin==\"null\"){\r\n");
      out.write("			alert(\"정상적인 접근이아닙니다.\");\r\n");
      out.write("			location.href=\"./index.jsp\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<!-- 최상단 끝-->\r\n");
      out.write("<!-- 상단-->\r\n");
      out.write("<nav class=\"navcss\">\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("   <div class=\"nav_div\">\r\n");
      out.write("        <ol>\r\n");
      out.write("            <li title=\"쇼핑몰 회원관리\"><a href=\"./admin_mainok.do\">쇼핑몰 회원관리</a></li>\r\n");
      out.write("            <li title=\"쇼핑몰 상품관리\"><a href=\"./plists.do\">쇼핑몰 상품관리</a></li>\r\n");
      out.write("            <li title=\"쇼핑몰 기본설정\"><a href=\"./admin_config.do\">쇼핑몰 기본설정</a></li>\r\n");
      out.write("        </ol>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- 상단-->\r\n");
      out.write("<main class=\"maincss\">\r\n");
      out.write("<section>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

List<memberDto> lists = (List<memberDto>) request.getAttribute("lists");

      out.write("\r\n");
      out.write(" <p>회원 리스트</p>\r\n");
      out.write("    <ol class=\"new_admin_title\">\r\n");
      out.write("        <li>NO</li>\r\n");
      out.write("        <li>고객명</li>\r\n");
      out.write("        <li>아이디</li>\r\n");
      out.write("        <li>전화번호</li>\r\n");
      out.write("        <li>이메일</li>\r\n");
      out.write("        <li>이메일 수신</li>\r\n");
      out.write("        <li>SMS 수신</li>\r\n");
      out.write("        <li>가입일자</li>\r\n");
      out.write("        <li>상태</li>\r\n");
      out.write("        <li>정지여부</li>\r\n");
      out.write("    </ol>\r\n");
      out.write("    ");
if(lists.size()==0){ 
      out.write("\r\n");
      out.write("    <ol class=\"new_admin_none\">\r\n");
      out.write("        <li>가입된 회원이 없습니다.</li>\r\n");
      out.write("    </ol>\r\n");
      out.write("    ");
} 
    else{
    	int w =0;
    	do{
    
      out.write("\r\n");
      out.write("    <ol class=\"new_admin_lists\">\r\n");
      out.write("        <li>");
      out.print(lists.get(w).getMidx());
      out.write("</li>\r\n");
      out.write("        <li>");
      out.print(lists.get(w).getMname());
      out.write("</li>\r\n");
      out.write("        <li>");
      out.print(lists.get(w).getMid());
      out.write("</li>\r\n");
      out.write("        <li>");
      out.print(lists.get(w).getMtel());
      out.write("</li>\r\n");
      out.write("        <li>");
      out.print(lists.get(w).getMemail());
      out.write("</li>\r\n");
      out.write("        <li>");
      out.print(lists.get(w).getMcmail());
      out.write("</li>\r\n");
      out.write("        <li>");
      out.print(lists.get(w).getMcsms());
      out.write("</li>\r\n");
      out.write("        <li>");
      out.print(lists.get(w).getMindate().substring(0, 10));
      out.write("</li>\r\n");
      out.write("        <li>");
      out.print(lists.get(w).getMuse());
      out.write("</li>\r\n");
      out.write("        <li>\r\n");
      out.write("        	<form id=\"ckF\" method=\"post\" action=\"./admin_mainok.do\" onsubmit=\"return ck_use();\">\r\n");
      out.write("	            <input type=\"submit\" value=\"정지\" name=\"muse\" class=\"new_addbtn1\" title=\"정지\">\r\n");
      out.write("	            <input type=\"submit\" value=\"해제\" name=\"muse\" class=\"new_addbtn2\" title=\"해제\">\r\n");
      out.write("	            <input type=\"hidden\" value=\"");
      out.print(lists.get(w).getMidx());
      out.write("\" name=\"idx\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ol>\r\n");
      out.write("    ");

    w++;
    }while(w < lists.size());
    }
    
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function ck_use(v){\r\n");
      out.write("		if(ckF.muse.value==\"\"){\r\n");
      out.write("			//alert(\"권한이 없습니다.\");\r\n");
      out.write("			//return false;\r\n");
      out.write("		}\r\n");
      out.write("		else{\r\n");
      out.write("			ckF.mmuse.value=ckF.muse.value;\r\n");
      out.write("			ckF.submit();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<section></section>\r\n");
      out.write("<section></section>\r\n");
      out.write("</main>\r\n");
      out.write("<!-- 하단 -->\r\n");
      out.write("<footer class=\"main_copyright\">\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write(" <div>\r\n");
      out.write("        Copyright ⓒ 2023 shopbag All rights reserved.\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- 하단 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
