/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-10-25 11:47:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/shop/./s_top.jsp", Long.valueOf(1698137451097L));
    _jspx_dependants.put("/shop/./login_content.jsp", Long.valueOf(1698234420229L));
    _jspx_dependants.put("/shop/./s_footer.jsp", Long.valueOf(1698117641832L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1693913616537L));
    _jspx_dependants.put("jar:file:/C:/Users/lee/Desktop/team/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/admin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

 Date lday = new Date();
 SimpleDateFormat lsf = new SimpleDateFormat("yyyyMMddHHmmss");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Shop Bag</title>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <link href=\"./css/index.css?v=");
      out.print(lsf.format(lday) );
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"./css/subpage.css?v=");
      out.print(lsf.format(lday) );
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("   <div class=\"navbar\">\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');

String usernm = (String) session.getAttribute("userName");

      out.write("    \r\n");
      out.write("  <a href=\"./shopmain.do\" id=\"logo\">\r\n");
      out.write("        <img src=\"./../images/logo.jpg\" width=\"149\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul id=\"menu\">\r\n");
      out.write("        ");

        if(usernm == "" || usernm == null){
        
      out.write("\r\n");
      out.write("          <li><a href=\"./login.do\">LOGIN</a></li>\r\n");
      out.write("          <li><a href=\"#\">MEMBER SHIP</a></li>\r\n");
      out.write("          <li><a href=\"#\">CART</a></li>\r\n");
      out.write("          <li><a href=\"#\">CUSTOMER CENTER</a></li>\r\n");
      out.write("        ");

        }
        else{
        
      out.write("\r\n");
      out.write("        <li>");
      out.print(usernm );
      out.write("님 환영합니다. <a href=\"./logoutok.do\">[로그아웃]</a></li>\r\n");
      out.write("       	<li><a href=\"#\">CART</a></li>\r\n");
      out.write("        <li><a href=\"#\">CUSTOMER CENTER</a></li>        	\r\n");
      out.write("        ");

        }
        
      out.write("\r\n");
      out.write("        </ul>");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write(" <main>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

 Date lc_day = new Date();
 SimpleDateFormat lc_sf = new SimpleDateFormat("yyyyMMddHHmmss");

      out.write("\r\n");
      out.write(" <div class=\"products\">\r\n");
      out.write("      <h3>MEMBER_LOGIN</h3>\r\n");
      out.write("      <div class=\"sub_view\">\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"loginview\">\r\n");
      out.write("          <span class=\"member_l\"></span>\r\n");
      out.write("          <span class=\"login\">\r\n");
      out.write("          <form id=\"loginForm\" method=\"post\" action=\"./loginok.do\" onsubmit=\"return login();\">  \r\n");
      out.write("          <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"table_login\">\r\n");
      out.write("          <tr>\r\n");
      out.write("          <td>\r\n");
      out.write("          <input type=\"text\" name=\"uid\" placeholder=\"아이디를 입력해주세요\" class=\"id\">\r\n");
      out.write("          </td>\r\n");
      out.write("          <td rowspan=\"2\">\r\n");
      out.write("          <input type=\"submit\" value=\"LOGIN\" class=\"btn1\">\r\n");
      out.write("          </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("          <td>\r\n");
      out.write("          <input type=\"password\" name=\"upw\" placeholder=\"패스워드를 입력해주세요\" class=\"id\">\r\n");
      out.write("          </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("              \r\n");
      out.write("          <div class=\"check1\">\r\n");
      out.write("          <input type=\"checkbox\" id=\"saveidbox\" onclick=\"saveid()\" id=\"l\"> <label for=\"l\" class=\"label_login\">아이디 저장 (테스트계정: test123/test123123)</label>\r\n");
      out.write("          </div>\r\n");
      out.write("          </form>\r\n");
      out.write("          <ul class=\"btns_login\">\r\n");
      out.write("	          <li><a class=\"a\" href=\"./agree.do\">회원가입</a></li>\r\n");
      out.write("	          <li><input type=\"button\" value=\"아이디 찾기\" class=\"a\"></li>\r\n");
      out.write("	          <li><input type=\"button\" value=\"비밀번호 찾기\" class=\"a1\"></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <form>    \r\n");
      out.write("          <span class=\"font1\">비회원 주문조회</span>\r\n");
      out.write("          <span class=\"search_login\">\r\n");
      out.write("              <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"table_login\">\r\n");
      out.write("              <tr>\r\n");
      out.write("              <td>\r\n");
      out.write("                  <input type=\"text\" placeholder=\"주문자명을 입력해주세요\" class=\"id\" tabindex=\"1\">\r\n");
      out.write("              </td>\r\n");
      out.write("              <td rowspan=\"2\">\r\n");
      out.write("              <input type=\"submit\" value=\"주문조회\" class=\"btn1\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                  <td>\r\n");
      out.write("                 <input type=\"text\" placeholder=\"주문번호를 8자리 입력해 주세요\" class=\"id\" maxlength=\"8\" tabindex=\"2\">\r\n");
      out.write("                  </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              </table>\r\n");
      out.write("              <label class=\"check1\">\r\n");
      out.write("              주문자명과 주문번호를 잊으신 경우, 고객센터로 문의하여 주시기 바랍니다.\r\n");
      out.write("          </label>\r\n");
      out.write("          </span>\r\n");
      out.write("          </form>\r\n");
      out.write("          </span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"./js/login_content.js?v=");
      out.print(lc_sf.format(lc_day));
      out.write("\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<footer>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("      <a href=\"http://facebook.com\">\r\n");
      out.write("        <img src=\"../images/facebook.png\"height=\"20\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"http://instagram.com\">\r\n");
      out.write("        <img src=\"../images/instagram.png\"height=\"20\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"http://twitter.com\">\r\n");
      out.write("        <img src=\"../images/twitter.png\"height=\"20\">\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section class=\"foot_section\"></section>\r\n");
      out.write("    <aside class=\"aside_footer\">\r\n");
      out.write("        <div class=\"div_footer\">\r\n");
      out.write("        <ul>\r\n");
      out.write("	        <li><img src=\"../images/foot_logo.png\"></li>\r\n");
      out.write("	        <li>\r\n");
      out.write("			회사명 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteInfo.site_corp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			대표자 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteInfo.site_ceo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			주소 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteInfo.site_address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br>\r\n");
      out.write("			고객센터 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteInfo.site_tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			상담시간 : \r\n");
      out.write("			E-Mail : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteInfo.site_mail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			사업자등록번호 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteInfo.site_corp_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br>\r\n");
      out.write("			통신판매업신고번호 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteInfo.site_register}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			개인정보보호책임자 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteInfo.site_security}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br>\r\n");
      out.write("			Copyright © 도메인명 All Rights Reserved.\r\n");
      out.write("	        </li>\r\n");
      out.write("        </ul>    \r\n");
      out.write("        </div>\r\n");
      out.write("    </aside>");
      out.write("  \r\n");
      out.write("</footer>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
